/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.elemency.Midi4J;

import org.junit.Test;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
//        aLibrary classUnderTest = new aLibrary();
//        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
