/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.elemency.VertxRtMidi;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
//        aLibrary classUnderTest = new aLibrary();
//        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
